
package Vistas;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import Controladores.*;
import DTO.Huesped;
import java.awt.event.KeyEvent;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmHuespedes extends javax.swing.JFrame {
    private ControladorHuesped controladorHuesped;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmHuespedes.class.getName());

    
    public FrmHuespedes() {
        configurarApariencia();
        initComponents();
        configurarTabla();
        personalizarDiseno();
        controladorHuesped = new ControladorHuesped();
        listarHuespedesTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBuscarHuespedes = new javax.swing.JTextField();
        btnNuevoHuesped = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaHuespedes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Huéspedes");
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(943, 691));

        jPanel1.setPreferredSize(new java.awt.Dimension(943, 691));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestión de Huéspedes");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(164, 164, 164));
        jLabel7.setText("Administrar los huéspedes del hospedaje");

        txtBuscarHuespedes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarHuespedesKeyReleased(evt);
            }
        });

        btnNuevoHuesped.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevoHuesped.setText("Nuevo Huésped");
        btnNuevoHuesped.addActionListener(this::btnNuevoHuespedActionPerformed);

        tablaHuespedes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "DNI", "Nombre", "Teléfono"
            }
        ));
        tablaHuespedes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaHuespedesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaHuespedes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevoHuesped))
                    .addComponent(txtBuscarHuespedes)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnNuevoHuesped))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(36, 36, 36)
                .addComponent(txtBuscarHuespedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 913, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 654, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoHuespedActionPerformed
        abrirDialogoNuevoHuesped();
    }//GEN-LAST:event_btnNuevoHuespedActionPerformed

    private void txtBuscarHuespedesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarHuespedesKeyReleased
        String texto = txtBuscarHuespedes.getText().trim().toLowerCase();
        try {
            List<Huesped> lista = controladorHuesped.listarHuespedes();
            DefaultTableModel modelo = (DefaultTableModel) tablaHuespedes.getModel();
            modelo.setRowCount(0);

            for (Huesped h : lista) {
                if (h.getNombres().toLowerCase().contains(texto) || h.getDni().contains(texto)) {
                    Object[] fila = new Object[]{
                        h.getIdHuesped(),
                        h.getDni(),
                        h.getNombres(),
                        h.getTelefono()
                    };
                    modelo.addRow(fila);
                }
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_txtBuscarHuespedesKeyReleased

    private void tablaHuespedesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaHuespedesMouseClicked
        if (evt.getClickCount() == 2) {
         
            int fila = tablaHuespedes.getSelectedRow();
            if (fila != -1) {
                // Obtenemos el DNI de la fila seleccionada
                String dni = tablaHuespedes.getValueAt(fila, 1).toString();

                // Obtener el ID del huésped desde el controlador
                Huesped h = controladorHuesped.buscarPorDni(dni);
                if (h != null) {
                    abrirDialogoEditarHuesped(h.getIdHuesped());
                }
            }
        }
    }//GEN-LAST:event_tablaHuespedesMouseClicked

    private void abrirDialogoEditarHuesped(int idHuesped) {
        try {
            // Obtener el huésped desde el controlador
            Huesped h = controladorHuesped.buscarHuesped(idHuesped);
            if (h == null) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "No se encontró el huésped.",
                        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            JDialog dialog = new JDialog(this, "Editar Huésped", true);
            dialog.setLayout(new BorderLayout());

            // Panel principal del formulario
            JPanel pnlForm = new JPanel();
            pnlForm.setLayout(new BoxLayout(pnlForm, BoxLayout.Y_AXIS));
            pnlForm.setBorder(BorderFactory.createEmptyBorder(25, 25, 25, 25));
            pnlForm.setBackground(Color.WHITE);

            JLabel lblTitulo = new JLabel("Editar Huésped");
            lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 20));
            lblTitulo.setAlignmentX(Component.LEFT_ALIGNMENT);
            pnlForm.add(lblTitulo);
            pnlForm.add(Box.createVerticalStrut(20));

            // Campos de texto con datos precargados
            JPanel pNombre = crearCampoEstilizado("Nombre Completo", "");
            JPanel pDni = crearCampoEstilizado("DNI / Identificación", "");
            JPanel pTelefono = crearCampoEstilizado("Teléfono", "");

            JTextField txtNombre = (JTextField) pNombre.getComponent(1);
            JTextField txtDni = (JTextField) pDni.getComponent(1);
            JTextField txtTelefono = (JTextField) pTelefono.getComponent(1);

            // Setear los valores actuales
            txtNombre.setText(h.getNombres());
            txtDni.setText(h.getDni());
            
            /*Por si se desea desactivar el campo de DNI al realizar una edición
            txtDni.setEditable(false);
            txtDni.setEnabled(false);*/

            
            txtTelefono.setText(h.getTelefono());

            // VALIDAR SOLO NÚMEROS
            txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent evt) {
                    soloNumeros(evt, txtDni, 12);
                }
            });

            txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
                @Override
                public void keyTyped(KeyEvent evt) {
                    soloNumeros(evt, txtTelefono, 9);
                }
            });
            
            pnlForm.add(pNombre);
            pnlForm.add(Box.createVerticalStrut(15));
            pnlForm.add(pDni);
            pnlForm.add(Box.createVerticalStrut(15));
            pnlForm.add(pTelefono);

            // Panel de botones
            JPanel pnlBotones = new JPanel(new FlowLayout(FlowLayout.RIGHT));
            pnlBotones.setBackground(Color.WHITE);
            pnlBotones.setBorder(BorderFactory.createEmptyBorder(0, 15, 15, 15));

            JButton btnCancelar = new JButton("Cancelar");
            JButton btnGuardar = new JButton("Guardar Cambios");

            // Estilo del botón guardar
            btnGuardar.setBackground(new Color(37, 99, 235));
            btnGuardar.setForeground(Color.WHITE);
            btnGuardar.setFont(new Font("Segoe UI", Font.BOLD, 13));

            // BOTÓN CANCELAR (secundario)
            btnCancelar.setBackground(new Color(241, 245, 249));
            btnCancelar.setForeground(new Color(30, 41, 59));
            btnCancelar.setFont(new Font("Segoe UI", Font.PLAIN, 13));
            btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            
            // Accion del boton cancelar
            btnCancelar.addActionListener(e -> dialog.dispose());

            // Accion del boton guardar
            btnGuardar.addActionListener(e -> {
                String nombre = txtNombre.getText().trim();
                String dni = txtDni.getText().trim();
                String telefono = txtTelefono.getText().trim();

                // Validaciones básicas
                if (nombre.isEmpty() || dni.isEmpty() || telefono.isEmpty()) {
                    javax.swing.JOptionPane.showMessageDialog(dialog,
                            "Todos los campos son obligatorios.",
                            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    return;
                }

                // Validacion de longitud del DNI y CE
                if (!(dni.length() == 8 || dni.length() == 12)) {
                    JOptionPane.showMessageDialog(dialog,
                            "El DNI debe tener 8 dígitos o el CE 12.",
                            "Error",
                            JOptionPane.ERROR_MESSAGE
                    );
                    return;
                }
                
                try {
                    // Actualizar los datos del huésped
                    h.setNombres(nombre);
                    h.setDni(dni);
                    h.setTelefono(telefono);

                    boolean exito = controladorHuesped.modificarHuesped(h);

                    if (exito) {
                        javax.swing.JOptionPane.showMessageDialog(dialog,
                                "Huésped actualizado correctamente.");
                        listarHuespedesTabla(); // Refrescar tabla
                        dialog.dispose();
                    } else {
                        javax.swing.JOptionPane.showMessageDialog(dialog,
                                "No se pudo actualizar el huésped.",
                                "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    }
                } catch (Exception ex) {
                    javax.swing.JOptionPane.showMessageDialog(dialog,
                            "Error: " + ex.getMessage(),
                            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                    ex.printStackTrace();
                }
            });

            pnlBotones.add(btnCancelar);
            pnlBotones.add(btnGuardar);

            // Agregar paneles al dialogo
            dialog.add(pnlForm, BorderLayout.CENTER);
            dialog.add(pnlBotones, BorderLayout.SOUTH);

            dialog.pack();
            dialog.setSize(400, 420);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al abrir el diálogo: " + ex.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private void configurarApariencia() {
        try {
            FlatIntelliJLaf.setup();
            // Configuración de bordes redondeados globales para componentes
            UIManager.put("Button.arc", 12);
            UIManager.put("Component.arc", 12);
            UIManager.put("TextComponent.arc", 12);
            UIManager.put("ScrollBar.trackArc", 999);
            UIManager.put("ScrollBar.thumbArc", 999);
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void configurarTabla() {
        DefaultTableModel modelo = new DefaultTableModel(
                new Object[]{"ID", "DNI", "NOMBRES", "TELÉFONO"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; //  ninguna celda editable
            }
        };

        tablaHuespedes.setModel(modelo);

        // Refuerzo extra (opcional pero recomendado)
        tablaHuespedes.setDefaultEditor(Object.class, null);
    }

    
    private void personalizarDiseno() {
        // 1. Fondo del panel principal
        jPanel1.setBackground(new Color(250, 251, 253));

        // 2. Títulos
        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 28));
        jLabel1.setForeground(new Color(30, 41, 59));

        jLabel7.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        jLabel7.setForeground(new Color(100, 116, 139));

        // 3. Campo de Búsqueda
        txtBuscarHuespedes.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Buscar por nombre o DNI...");
        txtBuscarHuespedes.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
        txtBuscarHuespedes.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        // 4. Botón "Nuevo Usuario"
        btnNuevoHuesped.setBackground(new Color(37, 99, 235));
        btnNuevoHuesped.setForeground(Color.WHITE);
        btnNuevoHuesped.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnNuevoHuesped.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        // Nota: El redondeo ya se aplica por el UIManager.put("Button.arc", 12)

        // 5. Personalización de la Tabla
        tablaHuespedes.setRowHeight(40);
        tablaHuespedes.setShowHorizontalLines(true);
        tablaHuespedes.setGridColor(new Color(241, 245, 249));
        tablaHuespedes.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        tablaHuespedes.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tablaHuespedes.getTableHeader().setBackground(Color.WHITE);
        tablaHuespedes.getTableHeader().setForeground(new Color(71, 85, 105));
        tablaHuespedes.setSelectionBackground(new Color(239, 246, 255));
        tablaHuespedes.setSelectionForeground(new Color(37, 99, 235));
        
        DefaultTableCellRenderer render = new DefaultTableCellRenderer();
        render.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 10));
        for (int i = 0; i < tablaHuespedes.getColumnCount(); i++) {
            tablaHuespedes.getColumnModel().getColumn(i).setCellRenderer(render);
        }

        // 6. ScrollPanes (CORRECCIÓN DEL ERROR 'arc')
        jScrollPane1.setBorder(null);
        jScrollPane2.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 1));
    }
    
    private void abrirDialogoNuevoHuesped() {
        JDialog dialog = new JDialog(this, "Registrar Nuevo Huésped", true);
        dialog.setLayout(new BorderLayout());

        // Panel principal del formulario
        JPanel pnlForm = new JPanel();
        pnlForm.setLayout(new BoxLayout(pnlForm, BoxLayout.Y_AXIS));
        pnlForm.setBorder(BorderFactory.createEmptyBorder(25, 25, 25, 25));
        pnlForm.setBackground(Color.WHITE);

        JLabel lblTitulo = new JLabel("Registrar Huésped");
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 20));
        lblTitulo.setAlignmentX(Component.LEFT_ALIGNMENT);
        pnlForm.add(lblTitulo);
        pnlForm.add(Box.createVerticalStrut(20));

        // Campos de texto
        JPanel pNombre = crearCampoEstilizado("Nombre Completo", "Ej: Juan Perez");
        JPanel pDni = crearCampoEstilizado("DNI / Identificación", "Número de 8 dígitos");
        JPanel pTelefono = crearCampoEstilizado("Teléfono", "Ej: 987654321");

        // Obtener los JTextField para poder leer los datos
        JTextField txtNombre = (JTextField) pNombre.getComponent(1);
        JTextField txtDni = (JTextField) pDni.getComponent(1);
        JTextField txtTelefono = (JTextField) pTelefono.getComponent(1);

        
        //VALIDACIONES DE SOLO NÚMEROS
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent evt) {
                soloNumeros(evt, txtDni, 12); // DNI o CE
            }
        });

        txtTelefono.addKeyListener(new java.awt.event.KeyAdapter() {
            @Override
            public void keyTyped(KeyEvent evt) {
                soloNumeros(evt, txtTelefono, 9); // Teléfono
            }
        });

        pnlForm.add(pNombre);
        pnlForm.add(Box.createVerticalStrut(15));
        pnlForm.add(pDni);
        pnlForm.add(Box.createVerticalStrut(15));
        pnlForm.add(pTelefono);

        // Panel de botones
        JPanel pnlBotones = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        pnlBotones.setBackground(Color.WHITE);
        pnlBotones.setBorder(BorderFactory.createEmptyBorder(0, 15, 15, 15));

        JButton btnCancelar = new JButton("Cancelar");
        JButton btnGuardar = new JButton("Guardar Huésped");

        // Estilo del botón guardar
        btnGuardar.setBackground(new Color(37, 99, 235));
        btnGuardar.setForeground(Color.WHITE);
        btnGuardar.setFont(new Font("Segoe UI", Font.BOLD, 13));

        // Acción del botón cancelar
        btnCancelar.addActionListener(e -> dialog.dispose());

        // Acción del botón guardar
        btnGuardar.addActionListener(e -> {
            String nombre = txtNombre.getText().trim();
            String dni = txtDni.getText().trim();
            String telefono = txtTelefono.getText().trim();

            // Validaciones básicas
            if (nombre.isEmpty() || dni.isEmpty() || telefono.isEmpty()) {
                javax.swing.JOptionPane.showMessageDialog(dialog,
                        "Todos los campos son obligatorios.",
                        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                return;
            }

            //Validacion de Longitud del dni y CE
            if (!(dni.length() == 8 || dni.length() == 12)) {
                JOptionPane.showMessageDialog(dialog,
                        "El DNI debe tener 8 dígitos o el CE 12.",
                        "Error",
                        JOptionPane.ERROR_MESSAGE
                );
                return;
            }

            //Validamos duplicado de DNI
            if (controladorHuesped.buscarPorDni(dni) != null) {
                JOptionPane.showMessageDialog(dialog,
                        "Ya existe un huésped con ese DNI",
                        "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }

            
            try {
                // Crear DTO y guardar usando el controlador
                Huesped h = new Huesped(dni, nombre, telefono);
                boolean exito = controladorHuesped.crearHuesped(h);

                if (exito) {
                    javax.swing.JOptionPane.showMessageDialog(dialog,
                            "Huésped registrado correctamente.");
                    listarHuespedesTabla(); // Refrescar tabla principal
                    dialog.dispose();
                } else {
                    javax.swing.JOptionPane.showMessageDialog(dialog,
                            "No se pudo registrar el huésped.",
                            "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception ex) {
                javax.swing.JOptionPane.showMessageDialog(dialog,
                        "Error: " + ex.getMessage(),
                        "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        });

        pnlBotones.add(btnCancelar);
        pnlBotones.add(btnGuardar);

        // Agregar paneles al dialogo
        dialog.add(pnlForm, BorderLayout.CENTER);
        dialog.add(pnlBotones, BorderLayout.SOUTH);

        dialog.pack();
        dialog.setSize(400, 420);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }


    private JPanel crearCampoEstilizado(String titulo, String placeholder) {
        JPanel p = new JPanel();
        p.setLayout(new BorderLayout(0, 5));
        p.setBackground(Color.WHITE);
        p.setAlignmentX(Component.LEFT_ALIGNMENT);

        JLabel lbl = new JLabel(titulo);
        lbl.setFont(new Font("Segoe UI", Font.BOLD, 12));
        lbl.setForeground(new Color(71, 85, 105));

        JTextField txt = new JTextField();
        txt.setPreferredSize(new Dimension(300, 30));
        txt.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, placeholder);

        p.add(lbl, BorderLayout.NORTH);
        p.add(txt, BorderLayout.CENTER);
        return p;
    }
    
    private void listarHuespedesTabla() {
        try {
            List<Huesped> lista = controladorHuesped.listarHuespedes();
            DefaultTableModel modelo = (DefaultTableModel) tablaHuespedes.getModel();
            modelo.setRowCount(0); // limpiar tabla

            for (Huesped h : lista) {
                Object[] fila = new Object[]{
                    h.getIdHuesped(),
                    h.getDni(), // Columna "DNI"
                    h.getNombres(), // Columna "Nombre"
                    h.getTelefono() // Columna "Teléfono"
                };
                modelo.addRow(fila);
            }
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Error al listar huéspedes: " + e.getMessage(),
                    "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
        }
    }

    private void soloNumeros(KeyEvent evt, JTextField txt, int maxLength) {
        char c = evt.getKeyChar();

        if (!Character.isDigit(c) && c != KeyEvent.VK_BACK_SPACE && c != KeyEvent.VK_DELETE) {
            evt.consume();
            return;
        }

        // Bloquear si supera longitud
        if (txt.getText().length() >= maxLength) {
            evt.consume();
        }
    }

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new FrmHuespedes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoHuesped;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaHuespedes;
    private javax.swing.JTextField txtBuscarHuespedes;
    // End of variables declaration//GEN-END:variables
}
