
package Vistas;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;


public class FrmHuespedes extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmHuespedes.class.getName());

    
    public FrmHuespedes() {
        configurarApariencia();
        initComponents();
        personalizarDiseno();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBuscarHuespedes = new javax.swing.JTextField();
        btnNuevoHuesped = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaHuespedes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión de Huéspedes");
        setPreferredSize(new java.awt.Dimension(913, 654));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestión de Huéspedes");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(164, 164, 164));
        jLabel7.setText("Administrar los huéspedes del hospedaje");

        btnNuevoHuesped.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevoHuesped.setText("Nuevo Huésped");
        btnNuevoHuesped.addActionListener(this::btnNuevoHuespedActionPerformed);

        tablaHuespedes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "DNI", "Nombre", "Teléfono", "Acciones"
            }
        ));
        jScrollPane2.setViewportView(tablaHuespedes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNuevoHuesped))
                    .addComponent(txtBuscarHuespedes)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 840, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnNuevoHuesped))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(36, 36, 36)
                .addComponent(txtBuscarHuespedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 924, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 670, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoHuespedActionPerformed
        abrirDialogoNuevoHuesped();
    }//GEN-LAST:event_btnNuevoHuespedActionPerformed

    private void configurarApariencia() {
        try {
            FlatIntelliJLaf.setup();
            // Configuración de bordes redondeados globales para componentes
            UIManager.put("Button.arc", 12);
            UIManager.put("Component.arc", 12);
            UIManager.put("TextComponent.arc", 12);
            UIManager.put("ScrollBar.trackArc", 999);
            UIManager.put("ScrollBar.thumbArc", 999);
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    private void personalizarDiseno() {
        // 1. Fondo del panel principal
        jPanel1.setBackground(new Color(250, 251, 253));

        // 2. Títulos
        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 28));
        jLabel1.setForeground(new Color(30, 41, 59));

        jLabel7.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        jLabel7.setForeground(new Color(100, 116, 139));

        // 3. Campo de Búsqueda
        txtBuscarHuespedes.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Buscar por nombre o DNI...");
        txtBuscarHuespedes.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
        txtBuscarHuespedes.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        // 4. Botón "Nuevo Usuario"
        btnNuevoHuesped.setBackground(new Color(37, 99, 235));
        btnNuevoHuesped.setForeground(Color.WHITE);
        btnNuevoHuesped.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnNuevoHuesped.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        // Nota: El redondeo ya se aplica por el UIManager.put("Button.arc", 12)

        // 5. Personalización de la Tabla
        tablaHuespedes.setRowHeight(40);
        tablaHuespedes.setShowHorizontalLines(true);
        tablaHuespedes.setGridColor(new Color(241, 245, 249));
        tablaHuespedes.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        tablaHuespedes.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tablaHuespedes.getTableHeader().setBackground(Color.WHITE);
        tablaHuespedes.getTableHeader().setForeground(new Color(71, 85, 105));
        tablaHuespedes.setSelectionBackground(new Color(239, 246, 255));
        tablaHuespedes.setSelectionForeground(new Color(37, 99, 235));
        
        DefaultTableCellRenderer render = new DefaultTableCellRenderer();
        render.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 10));
        for (int i = 0; i < tablaHuespedes.getColumnCount(); i++) {
            tablaHuespedes.getColumnModel().getColumn(i).setCellRenderer(render);
        }

        // 6. ScrollPanes (CORRECCIÓN DEL ERROR 'arc')
        jScrollPane1.setBorder(null);
        jScrollPane2.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 1));
    }
    
    private void abrirDialogoNuevoHuesped() {
        JDialog dialog = new JDialog(this, "Crear Nuevo Usuario", true);
        dialog.setLayout(new BorderLayout());
        
        JPanel pnlForm = new JPanel();
        pnlForm.setLayout(new BoxLayout(pnlForm, BoxLayout.Y_AXIS));
        pnlForm.setBorder(BorderFactory.createEmptyBorder(25, 25, 25, 25));
        pnlForm.setBackground(Color.WHITE);

        JLabel lblTitulo = new JLabel("Registrar Huésped");
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 20));
        lblTitulo.setAlignmentX(Component.LEFT_ALIGNMENT);
        
        pnlForm.add(lblTitulo);
        pnlForm.add(Box.createVerticalStrut(20));
        pnlForm.add(crearCampoEstilizado("Nombre Completo", "Ej: Juan Perez"));
        pnlForm.add(Box.createVerticalStrut(15));
        pnlForm.add(crearCampoEstilizado("DNI / Identificación", "Número de 8 dígitos"));
        pnlForm.add(Box.createVerticalStrut(15));
        pnlForm.add(crearCampoEstilizado("Teléfono", "Ej: 987654321"));
        
        JPanel pnlBotones = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        pnlBotones.setBackground(Color.WHITE);
        pnlBotones.setBorder(BorderFactory.createEmptyBorder(0, 15, 15, 15));
        
        JButton btnCancelar = new JButton("Cancelar");
        JButton btnGuardar = new JButton("Guardar Huesped");
        btnGuardar.setBackground(new Color(37, 99, 235));
        btnGuardar.setForeground(Color.WHITE);
        btnGuardar.setFont(new Font("Segoe UI", Font.BOLD, 13));

        btnCancelar.addActionListener(e -> dialog.dispose());
        btnGuardar.addActionListener(e -> {
            // Lógica de guardado aquí
            dialog.dispose();
        });

        pnlBotones.add(btnCancelar);
        pnlBotones.add(btnGuardar);

        dialog.add(pnlForm, BorderLayout.CENTER);
        dialog.add(pnlBotones, BorderLayout.SOUTH);
        
        dialog.pack();
        dialog.setSize(400, 420);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    private JPanel crearCampoEstilizado(String titulo, String placeholder) {
        JPanel p = new JPanel();
        p.setLayout(new BorderLayout(0, 5));
        p.setBackground(Color.WHITE);
        p.setAlignmentX(Component.LEFT_ALIGNMENT);

        JLabel lbl = new JLabel(titulo);
        lbl.setFont(new Font("Segoe UI", Font.BOLD, 12));
        lbl.setForeground(new Color(71, 85, 105));

        JTextField txt = new JTextField();
        txt.setPreferredSize(new Dimension(300, 30));
        txt.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, placeholder);

        p.add(lbl, BorderLayout.NORTH);
        p.add(txt, BorderLayout.CENTER);
        return p;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new FrmHuespedes().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoHuesped;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaHuespedes;
    private javax.swing.JTextField txtBuscarHuespedes;
    // End of variables declaration//GEN-END:variables
}
