
package Vistas;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.Font;
import javax.swing.BorderFactory;
import javax.swing.Box;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import Controladores.*;
import DTO.Usuario;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FrmUsuarios extends javax.swing.JFrame {
    
    private ControladorUsuario controladorUsuario;
    private DefaultTableModel modelo;
    // Campos del formulario
    private JTextField txtUsername;
    private JTextField txtPassword;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FrmUsuarios.class.getName());

    
    public FrmUsuarios() {
        configurarApariencia();
        initComponents();
        personalizarDiseno();
        controladorUsuario = new ControladorUsuario();
        inicializarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtBuscarUsuario = new javax.swing.JTextField();
        btnNuevoUsuario = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaUsuarios = new javax.swing.JTable();

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gestión de Usuarios");

        jPanel1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jPanel1KeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gestión de Usuarios");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(164, 164, 164));
        jLabel7.setText("Administrar usuarios del sistema");

        txtBuscarUsuario.addActionListener(this::txtBuscarUsuarioActionPerformed);
        txtBuscarUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarUsuarioKeyReleased(evt);
            }
        });

        btnNuevoUsuario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNuevoUsuario.setText("Nuevo Usuario");
        btnNuevoUsuario.addActionListener(this::btnNuevoUsuarioActionPerformed);

        tablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Usuario", "Rol", "Estado"
            }
        ));
        tablaUsuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaUsuariosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tablaUsuarios);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 388, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 345, Short.MAX_VALUE)
                        .addComponent(btnNuevoUsuario))
                    .addComponent(txtBuscarUsuario)
                    .addComponent(jScrollPane2))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(btnNuevoUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(36, 36, 36)
                .addComponent(txtBuscarUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoUsuarioActionPerformed
        abrirDialogoNuevoUsuario();
    }//GEN-LAST:event_btnNuevoUsuarioActionPerformed

    private void jPanel1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel1KeyReleased

    private void txtBuscarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarUsuarioActionPerformed

    private void txtBuscarUsuarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarUsuarioKeyReleased
        buscarUsuarios();
    }//GEN-LAST:event_txtBuscarUsuarioKeyReleased

    private void tablaUsuariosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaUsuariosMouseClicked
        // TODO add your handling code here:if(evt.getClickCount() == 2){ // doble click
            int fila = tablaUsuarios.getSelectedRow();
            if(fila != -1){
                int idUsuario = (int) modelo.getValueAt(fila, 0);
                Usuario u = controladorUsuario.buscarUsuario(idUsuario);
                abrirDialogoEditarUsuario(u);
        }
        
    }//GEN-LAST:event_tablaUsuariosMouseClicked

    private void abrirDialogoEditarUsuario(Usuario u) {
        JDialog dialog = new JDialog(this, "Editar Usuario", true);
        dialog.setLayout(new BorderLayout());

        JPanel pnlForm = new JPanel();
        pnlForm.setLayout(new BoxLayout(pnlForm, BoxLayout.Y_AXIS));
        pnlForm.setBorder(BorderFactory.createEmptyBorder(25, 25, 25, 25));
        pnlForm.setBackground(Color.WHITE);

        JLabel lblTitulo = new JLabel("Editar Usuario");
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 20));
        lblTitulo.setAlignmentX(Component.LEFT_ALIGNMENT);
        pnlForm.add(lblTitulo);
        pnlForm.add(Box.createVerticalStrut(20));

        // Solo nombre de usuario
        JTextField txtUser = new JTextField(u.getUsername());
        txtUser.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Ej: Admin");

        JPanel pnlUsuario = new JPanel(new BorderLayout(0, 5));
        pnlUsuario.setBackground(Color.WHITE);
        JLabel lblUser = new JLabel("Usuario");
        lblUser.setFont(new Font("Segoe UI", Font.BOLD, 12));
        pnlUsuario.add(lblUser, BorderLayout.NORTH);
        pnlUsuario.add(txtUser, BorderLayout.CENTER);

        pnlForm.add(pnlUsuario);

        // Botones
        JPanel pnlBotones = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        pnlBotones.setBackground(Color.WHITE);
        JButton btnCancelar = new JButton("Cancelar");
        JButton btnGuardar = new JButton("Guardar");
        btnGuardar.setBackground(new Color(37, 99, 235));
        btnGuardar.setForeground(Color.WHITE);

        // BOTÓN CANCELAR (secundario)
        btnCancelar.setBackground(new Color(241, 245, 249));
        btnCancelar.setForeground(new Color(30, 41, 59));
        btnCancelar.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
        btnCancelar.addActionListener(e -> dialog.dispose());
        btnGuardar.addActionListener(e -> {
            if (txtUser.getText().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Complete el campo", "Advertencia", JOptionPane.WARNING_MESSAGE);
                return;
            }
            u.setUsername(txtUser.getText().trim());
            controladorUsuario.modificarUsuario(u);
            listarUsuarios();
            dialog.dispose();
        });

        pnlBotones.add(btnCancelar);
        pnlBotones.add(btnGuardar);

        dialog.add(pnlForm, BorderLayout.CENTER);
        dialog.add(pnlBotones, BorderLayout.SOUTH);

        dialog.setSize(400, 200);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    private void buscarUsuarios() {
        String texto = txtBuscarUsuario.getText().trim();
        modelo.setRowCount(0);

        for (Usuario u : controladorUsuario.buscarUsuarios(texto)) {
            modelo.addRow(new Object[]{
                u.getIdUsuario(),
                u.getUsername(),
                u.getRol(),
                u.getEstado()
            });
        }
    }

    
    private void configurarApariencia() {
        try {
            FlatIntelliJLaf.setup();
            // Configuración de bordes redondeados globales para componentes
            UIManager.put("Button.arc", 12);
            UIManager.put("Component.arc", 12);
            UIManager.put("TextComponent.arc", 12);
            UIManager.put("ScrollBar.trackArc", 999);
            UIManager.put("ScrollBar.thumbArc", 999);
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    private void inicializarTabla() {
        modelo = new DefaultTableModel(
                new String[]{"ID", "Usuario", "Rol", "Estado"}, 0
        ) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };

        tablaUsuarios.setModel(modelo);
        listarUsuarios();
    }

    private void listarUsuarios() {
        modelo.setRowCount(0);

        for (Usuario u : controladorUsuario.listarUsuarios()) {
            modelo.addRow(new Object[]{
                u.getIdUsuario(),
                u.getUsername(),
                u.getRol(),
                u.getEstado()
            });
        }
    }


    
    private void personalizarDiseno() {
        // 1. Fondo del panel principal
        jPanel1.setBackground(new Color(250, 251, 253));

        // 2. Títulos
        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 28));
        jLabel1.setForeground(new Color(30, 41, 59));

        jLabel7.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        jLabel7.setForeground(new Color(100, 116, 139));

        // 3. Campo de Búsqueda
        txtBuscarUsuario.putClientProperty(FlatClientProperties.PLACEHOLDER_TEXT, "Buscar por nombre de usuario...");
        txtBuscarUsuario.putClientProperty(FlatClientProperties.TEXT_FIELD_SHOW_CLEAR_BUTTON, true);
        txtBuscarUsuario.setFont(new Font("Segoe UI", Font.PLAIN, 14));

        // 4. Botón "Nuevo Usuario"
        btnNuevoUsuario.setBackground(new Color(37, 99, 235));
        btnNuevoUsuario.setForeground(Color.WHITE);
        btnNuevoUsuario.setFont(new Font("Segoe UI", Font.BOLD, 14));
        btnNuevoUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        // Nota: El redondeo ya se aplica por el UIManager.put("Button.arc", 12)

        // 5. Personalización de la Tabla
        tablaUsuarios.setRowHeight(40);
        tablaUsuarios.setShowHorizontalLines(true);
        tablaUsuarios.setGridColor(new Color(241, 245, 249));
        tablaUsuarios.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        tablaUsuarios.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 13));
        tablaUsuarios.getTableHeader().setBackground(Color.WHITE);
        tablaUsuarios.getTableHeader().setForeground(new Color(71, 85, 105));
        tablaUsuarios.setSelectionBackground(new Color(239, 246, 255));
        tablaUsuarios.setSelectionForeground(new Color(37, 99, 235));
        
        DefaultTableCellRenderer render = new DefaultTableCellRenderer();
        render.setBorder(BorderFactory.createEmptyBorder(0, 10, 0, 10));
        for (int i = 0; i < tablaUsuarios.getColumnCount(); i++) {
            tablaUsuarios.getColumnModel().getColumn(i).setCellRenderer(render);
        }

        // 6. ScrollPanes (CORRECCIÓN DEL ERROR 'arc')
        jScrollPane1.setBorder(null);
        jScrollPane2.setBorder(BorderFactory.createLineBorder(new Color(226, 232, 240), 1));
    }

    private void abrirDialogoNuevoUsuario() {
        JDialog dialog = new JDialog(this, "Nuevo Usuario", true);
        dialog.setLayout(new BorderLayout());

        JPanel pnlForm = new JPanel();
        pnlForm.setLayout(new BoxLayout(pnlForm, BoxLayout.Y_AXIS));
        pnlForm.setBorder(BorderFactory.createEmptyBorder(25, 25, 25, 25));
        pnlForm.setBackground(Color.WHITE);

        JLabel lblTitulo = new JLabel("Registrar Usuario");
        lblTitulo.setFont(new Font("Segoe UI", Font.BOLD, 20));
        lblTitulo.setAlignmentX(Component.LEFT_ALIGNMENT);

        pnlForm.add(lblTitulo);
        pnlForm.add(Box.createVerticalStrut(20));

        // Usuario
        pnlForm.add(crearCampoUsuario());
        pnlForm.add(Box.createVerticalStrut(15));

        // Contraseña
        pnlForm.add(crearCampoPassword());

        JPanel pnlBotones = new JPanel(new FlowLayout(FlowLayout.RIGHT));
        pnlBotones.setBackground(Color.WHITE);

        JButton btnCancelar = new JButton("Cancelar");
        JButton btnGuardar = new JButton("Guardar");

        btnGuardar.setBackground(new Color(37, 99, 235));
        btnGuardar.setForeground(Color.WHITE);

         // BOTÓN CANCELAR (secundario)
        btnCancelar.setBackground(new Color(241, 245, 249));
        btnCancelar.setForeground(new Color(30, 41, 59));
        btnCancelar.setFont(new Font("Segoe UI", Font.PLAIN, 13));
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        
        btnCancelar.addActionListener(e -> dialog.dispose());

        btnGuardar.addActionListener(e -> guardarUsuario(dialog));

        pnlBotones.add(btnCancelar);
        pnlBotones.add(btnGuardar);

        dialog.add(pnlForm, BorderLayout.CENTER);
        dialog.add(pnlBotones, BorderLayout.SOUTH);

        dialog.setSize(400, 300);
        dialog.setLocationRelativeTo(this);
        dialog.setVisible(true);
    }

    private void guardarUsuario(JDialog dialog) {
        if (txtUsername.getText().trim().isEmpty()
                || txtPassword.getText().trim().isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Complete todos los campos",
                    "Advertencia",
                    JOptionPane.WARNING_MESSAGE
            );
            return;
        }

        try {
            Usuario u = new Usuario();
            u.setUsername(txtUsername.getText().trim());
            u.setPassword(txtPassword.getText().trim());
            u.setRol("USUARIO"); // por ahora
            u.setEstado("ACTIVO");

            controladorUsuario.crearUsuario(u);
            listarUsuarios();
            txtUsername.setText("");
            txtPassword.setText("");
            txtUsername.requestFocus();
            dialog.dispose();

        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    ex.getMessage(),
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }


    private JPanel crearCampoUsuario() {
        JPanel p = new JPanel(new BorderLayout(0, 5));
        p.setBackground(Color.WHITE);

        JLabel lbl = new JLabel("Usuario");
        lbl.setFont(new Font("Segoe UI", Font.BOLD, 12));

        txtUsername = new JTextField();
        txtUsername.putClientProperty(
                FlatClientProperties.PLACEHOLDER_TEXT, "Ej: Admin"
        );

        p.add(lbl, BorderLayout.NORTH);
        p.add(txtUsername, BorderLayout.CENTER);
        return p;
    }

    private JPanel crearCampoPassword() {
        JPanel p = new JPanel(new BorderLayout(0, 5));
        p.setBackground(Color.WHITE);

        JLabel lbl = new JLabel("Contraseña");
        lbl.setFont(new Font("Segoe UI", Font.BOLD, 12));

        txtPassword = new JTextField();
        txtPassword.putClientProperty(
                FlatClientProperties.PLACEHOLDER_TEXT, "********"
        );

        p.add(lbl, BorderLayout.NORTH);
        p.add(txtPassword, BorderLayout.CENTER);
        return p;
    }

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new FrmUsuarios().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaUsuarios;
    private javax.swing.JTextField txtBuscarUsuario;
    // End of variables declaration//GEN-END:variables
}
